name: Build sb binary
on:
  workflow_dispatch:
  push:
    paths:
      - 'sb.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup venv
        run: mkdir build

      - name: Setup venv
        run: cd build && python3.10 -m venv venv

      - name: Install Dependencies
        run: ./build/venv/bin/pip install -r requirements.txt

      - name: List Pip modules
        run: ./build/venv/bin/pip list

      - name: Compile binary
        run: cd build && ./venv/bin/python -m nuitka ../sb.py --onefile -o sb

      - name: Copy binary and purge build directory
        run: cp ./build/sb sb && rm -rf ./build

      - name: chmod sb
        run: chmod +x sb

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Continuous Integration
          author_email: username@users.noreply.github.com
          message: 'Continuous Integration Updated Binary'
          add: 'sb'

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
